version: '3'
services:
  hostedStorage:
    container_name: deedmob-hosted-storage
    build:
      context: ./hostedStorage
    image: deedmob-hosted-storage:latest
    ports:
      - 3000:3000

  application:
    container_name: deedmob-app
    build:
      context: ./application
    image: deedmob-app:latest
    ports:
      -9229:9229

networks:
  default:
    name: deedmob-network